sonar.projectKey=validation-platform
sonar.projectName=Validation Platform
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=Backend/admin_config,Frontend/src
sonar.tests=Backend/admin_config/tests,Frontend/src
sonar.test.inclusions=Backend/admin_config/tests/**/*.py,Frontend/src/**/*.test.js,Frontend/src/**/*.test.jsx

sonar.exclusions=\
  Backend/admin_config/tests/**,\
  Backend/admin_config/migrations/**,\
  Backend/.venv/**,\
  Backend/gammes/**,\
  Frontend/src/**/*.test.js,\
  Frontend/src/**/*.test.jsx,\
  Frontend/node_modules/**,\
  Frontend/dist/**,\
  Frontend/coverage/**

sonar.coverage.exclusions=\
  Backend/admin_config/admin.py,\
  Backend/admin_config/apps.py,\
  Backend/admin_config/migrations/**,\
  Backend/admin_config/tests/**,\
  Frontend/src/main.jsx,\
  Frontend/src/**/*.test.js,\
  Frontend/src/**/*.test.jsx

sonar.python.coverage.reportPaths=Backend/coverage.xml
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info
