# Generated by Django 6.0.5 on 2026-06-03 11:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlocResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_bloc', models.CharField(max_length=255)),
                ('resultat', models.CharField(choices=[('Non_coté', 'Non coté'), ('OK', 'OK'), ('NOK mineur', 'NOK mineur'), ('NOK', 'NOK'), ('A_coter', 'À coter')], max_length=20)),
                ('commentaires', models.JSONField(default=list)),
                ('date_sauvegarde', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FonctionGamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('access_level', models.CharField(choices=[('ADMIN', 'Admin'), ('PPL', 'PPL'), ('VALIDEUR', 'Valideur'), ('VISITEUR', 'Visiteur')], default='VISITEUR', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='True = role système, ne doit pas être supprimé')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LigneBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveIntegerField()),
                ('resultat', models.CharField(choices=[('Non_coté', 'Non coté'), ('OK', 'OK'), ('NOK mineur', 'NOK mineur'), ('NOK', 'NOK'), ('A_coter', 'À coter')], max_length=20)),
                ('commentaires', models.JSONField(default=list)),
                ('date_sauvegarde', models.DateTimeField(auto_now=True)),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='admin_config.blocresultat')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=255)),
                ('nombre_vehicules', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('architectures', models.ManyToManyField(blank=True, related_name='projets', to='admin_config.architecture')),
                ('motorisations', models.ManyToManyField(blank=True, related_name='projets', to='admin_config.motorisation')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='admin_config.projet')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_config.role')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmq', models.CharField(max_length=100, unique=True)),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motorisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicules', to='admin_config.motorisation')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='admin_config.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pistes', models.CharField(blank=True, max_length=255, null=True)),
                ('boitiers', models.CharField(blank=True, max_length=255)),
                ('nombre_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CONFIG', 'Configurer'), ('NOT_CONFIG', 'Non configuré'), ('CANCEL', 'Annulé')], default='NOT_CONFIG', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('fichier_gamme', models.FileField(blank=True, null=True, upload_to='gammes/fichiers/')),
                ('fichier_associe', models.FileField(blank=True, null=True, upload_to='gammes/fichiers_associes/')),
                ('original_filename', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('original_associe_filename', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fonction_gamme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_config.fonctiongamme')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gammes', to='admin_config.projet')),
                ('type_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_config.typeprocedure')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gammes', to='admin_config.vehicule')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='EVComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_code', models.CharField(max_length=150)),
                ('commentaire', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_comments', to=settings.AUTH_USER_MODEL)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_comments', to='admin_config.gamme')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ev_code'], name='admin_confi_ev_code_e3de44_idx'), models.Index(fields=['gamme', 'ev_code'], name='admin_confi_gamme_i_b79ed4_idx')],
            },
        ),
        migrations.CreateModel(
            name='GammeGeneralComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_commentaire', models.CharField(choices=[('BESOINS', 'Besoins techniques'), ('PISTES', 'Pistes')], max_length=30)),
                ('commentaire', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_comments', to='admin_config.gamme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamme_general_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gamme', 'type_commentaire'], name='admin_confi_gamme_i_7f4bf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='StepValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_code', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('step_code', models.CharField(db_index=True, max_length=150)),
                ('cotation', models.CharField(choices=[('A_coter', 'À coter'), ('OK', 'OK'), ('NOK_mineur', 'NOK Mineur'), ('NOK', 'NOK'), ('Non_coté', 'Non coté')], max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_validations', to='admin_config.gamme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gamme', 'ev_code'], name='admin_confi_gamme_i_6086d8_idx'), models.Index(fields=['gamme', 'ev_code', 'step_code'], name='admin_confi_gamme_i_987d05_idx'), models.Index(fields=['step_code'], name='admin_confi_step_co_1231ba_idx')],
            },
        ),
    ]
