# Generated by Django 6.0.5 on 2026-06-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0007_emailotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='admin_confi_user_id_cbc24d_idx',
            old_name='admin_confi_user_id_4fd1e3_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='admin_confi_email_d8e210_idx',
            old_name='admin_confi_email_6a7861_idx',
        ),
    ]
