# Generated by Codex on 2026-06-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_config", "0010_backgroundjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="GammeParsedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("STARTED", "En cours"),
                            ("SUCCESS", "Termine"),
                            ("FAILURE", "Echoue"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("parser_version", models.PositiveIntegerField(default=1)),
                (
                    "file_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gamme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_data",
                        to="admin_config.gamme",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="gammeparseddata",
            index=models.Index(
                fields=["status"],
                name="admin_confi_status_098adf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gammeparseddata",
            index=models.Index(
                fields=["parser_version", "file_fingerprint"],
                name="admin_confi_parser__248d96_idx",
            ),
        ),
    ]
