# Generated by Django 6.0.6 on 2026-06-29 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0012_emailjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('USER_AFFECTED', 'Utilisateur affecte'), ('PROJECT_ASSIGNED', 'Projet affecte'), ('GAMME_ADDED_TO_PROJECT', 'Gamme ajoutee au projet'), ('GAMME_STARTED', 'Debut de gamme'), ('GAMME_FINISHED', 'Fin de gamme')], max_length=50)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admin_config.projet')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='admin_confi_recipie_e5a6d9_idx'), models.Index(fields=['type'], name='admin_confi_type_885f20_idx')],
            },
        ),
    ]
