# Generated by Django 6.0.5 on 2026-06-05 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0003_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEVComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_code', models.CharField(max_length=255)),
                ('commentaire', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='evcomment',
            name='admin_confi_ev_code_e3de44_idx',
        ),
        migrations.RemoveIndex(
            model_name='evcomment',
            name='admin_confi_gamme_i_b79ed4_idx',
        ),
        migrations.AlterModelOptions(
            name='stepmeasuredresultcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='stepmeasuredresultcomment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='globalevcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EVComment',
        ),
    ]
