# Generated by Django 6.0.5 on 2026-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0004_globalevcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamme',
            name='nom_gamme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
