# Generated by Django 6.0.6 on 2026-06-23 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0009_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('PROJECT_KPI', 'Export KPI Projet'), ('GAMME_KPI', 'Export KPI Gamme')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('STARTED', 'En cours'), ('SUCCESS', 'Termine'), ('FAILURE', 'Echoue')], default='PENDING', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='jobs/kpi/')),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
