ADMIN_PPL_COMMON_ACTIONS = frozenset(
    {
        "GAMMES_IMPORTED",
        "GAMME_CREATED",
        "GAMME_UPDATED",
        "GAMME_DELETED",
        "GAMME_STATUS_UPDATED",
        "GAMMES_REORDERED",
        "GAMME_EXPORTED",
        "GLOBAL_EV_COMMENT_CREATED",
        "GLOBAL_EV_COMMENT_UPDATED",
        "GLOBAL_EV_COMMENT_DELETED",
        "GAMME_GENERAL_COMMENT_CREATED",
        "GAMME_GENERAL_COMMENT_UPDATED",
        "GAMME_GENERAL_COMMENT_DELETED",
        "MEASURED_RESULT_COMMENT_CREATED",
        "MEASURED_RESULT_COMMENT_UPDATED",
        "MEASURED_RESULT_COMMENT_DELETED",
    }
)

ADMIN_VALIDEUR_COMMON_ACTIONS = frozenset(
    {
        "STEP_VALIDATION_CREATED",
        "GAMME_EXPORTED",
        "GLOBAL_EV_COMMENT_CREATED",
        "GLOBAL_EV_COMMENT_UPDATED",
        "GLOBAL_EV_COMMENT_DELETED",
        "GAMME_GENERAL_COMMENT_CREATED",
        "GAMME_GENERAL_COMMENT_UPDATED",
        "GAMME_GENERAL_COMMENT_DELETED",
        "MEASURED_RESULT_COMMENT_CREATED",
        "MEASURED_RESULT_COMMENT_UPDATED",
        "MEASURED_RESULT_COMMENT_DELETED",
    }
)

VISIBLE_AUDIT_ACTIONS = (
    ADMIN_PPL_COMMON_ACTIONS | ADMIN_VALIDEUR_COMMON_ACTIONS
)
